controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#indexPrueba:
    #path: /prueba
    #controller: App\Controller\DefaultController::index
#index1:
    #path: /uno
    #controller: App\Controller\DefaultController::index1